### ISSUE TITLE
How to configure max_connections  of postgresql?

### ISSUE THREAD

**Issue by samdai** [cloudfoundry-community/postgresql-docker-boshrelease#11]
The default value 100 of max_connections is not enough for my application, I want to change this number bigger, how do I configure it in postgresql-docker-boshrelease?

**Comment by drnic** [comment]
Sadly at the moment the containers do not have a built in way to configure the `postgresql.conf` file. But it would not be hard to implement.

Couple of tid bits of info:
- any parameters passed from CF via `cf create-service postgresql94 free xxx -c '{"MAX_CONNECTIONS": 500}'` are converted into environment variables within the running container (e.g. `$MAX_CONNECTIONS` would be set to `500`)
- you can also arbitrarily set an environment variable for all containers for a specific service plan. For example:

``` yaml
        plans:
          - id: '58dc3912-6e11-11e5-96cc-6c4008a663f0'
            name: 'free'
            container:
              backend: 'docker'
              image: cfcommunity/postgresql
              tag: "9.5"
              persistent_volumes:
                - '/data'
              environment:
              - 'MAX_CONNECTIONS=500'
```

(see https://github.com/cloudfoundry-community/cf-containers-broker/blob/master/app/models/docker_manager.rb#L327-L333)

Finally, you could test for an environment variable and then do a search-replace into `postgresql.conf` at start time, like we do here: https://github.com/cloudfoundry-community/postgresql-docker-boshrelease/blob/master/images/postgresql94/scripts/run.sh#L12

E.g. perhaps try adding something like (written without testing):

```
if [[ "${MAX_CONNECTIONS}X" != "X" ]]; then
  sed -i -e"s/^.*max_connections =.*$/max_connections = $MAX_CONNECTIONS/" $DATA_DIR/postgresql.conf
fi
```
